In [1]:
cd Documents/Workshop/DeepLearning/

[WinError 3] The system cannot find the path specified: 'Documents/Workshop/DeepLearning/'
C:\Users\aryan\Documents\Workshop\DeepLearning


# Importing the Libraries for Data Preprocessing

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importing the Data Set

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [4]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

### Creation of the Matrix of Features and Dependent variable Vector

In [5]:
X = dataset.iloc[:, 3:13].values
Y = dataset.iloc[:, 13].values

### Seperating out / Dealing with the Categorical Variable

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

### Dealing with the Country categorical variable

In [7]:
labelEncoder_X_Country = LabelEncoder()
X[:, 1] = labelEncoder_X_Country.fit_transform(X[:, 1])

### Dealing with the Gender categorical variable

In [8]:
labelEncoder_X_Gender = LabelEncoder()
X[:, 2] = labelEncoder_X_Gender.fit_transform(X[:, 2])

In [9]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\aryan\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\aryan\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


#### To avoid the Dummy variable trap

In [10]:
X = X[:, 1:]

### Splitting the data into Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

### Scaling the Data ( Feature Scaling )

In [12]:
from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
X_train = SC.fit_transform(X_train)
X_test = SC.transform(X_test)

## Finally Done with the Data Preprocessing ! Kudos Everyone !!

# Creating our First Neural Network ( ANN )

### Importing Keras, A library using which we will create the Neural Network

In [14]:
import keras

Using TensorFlow backend.


In [15]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [16]:
Our_Classifier = Sequential()

In [17]:
Our_Classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

C:\Users\aryan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [18]:
Our_Classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

C:\Users\aryan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [19]:
Our_Classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\Users\aryan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [20]:
Our_Classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [22]:
Our_Classifier.fit(X_train, Y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4816 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 80us/step - loss: 0.4253 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.4167 - accuracy: 0.8267
Epoch 4/100
8000/8000 [==============================] - 1s 81us/step - loss: 0.4110 - accuracy: 0.8340
Epoch 5/100
8000/8000 [==============================] - 1s 81us/step - loss: 0.4075 - accuracy: 0.8342
Epoch 6/100
8000/8000 [==============================] - 1s 84us/step - loss: 0.4051 - accuracy: 0.8363
Epoch 7/100
8000/8000 [==============================] - 1s 83us/step - loss: 0.4028 - accuracy: 0.8347
Epoch 8/100
8000/8000 [==============================] - 1s 83us/step - loss: 0.4015 - accuracy: 0.8354
Epoch 9/100
8000/8000 [==============================] - 1s 82us/step - loss: 0.4006 - accuracy: 0.8338
Epoch 10/100
8000/8000 [==============================] - 1s 83

In [23]:
Y_predicted = Our_Classifier.predict(X_test)

In [24]:
Y_predicted

array([[0.24968609],
       [0.25502047],
       [0.17177734],
       ...,
       [0.22528037],
       [0.22183317],
       [0.17674506]], dtype=float32)

In [25]:
Y_predicted = (Y_predicted>0.5)

In [26]:
Y_predicted

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [31]:
Y_predicted[345]

array([ True])

In [33]:
from sklearn.metrics import confusion_matrix
ConfusionMatrix = confusion_matrix(Y_test, Y_predicted)

In [34]:
ConfusionMatrix

array([[1517,   78],
       [ 192,  213]], dtype=int64)